function M = myMassMatrix_test(theta1,theta2,theta3,m1,m2,m3,l1,l2,l3,g)
%MYMASSMATRIX_TEST
%    M = MYMASSMATRIX_TEST(THETA1,THETA2,THETA3,M1,M2,M3,L1,L2,L3,G)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    24-Jul-2019 11:11:35

t2 = m2+m3;
t3 = -theta2;
t4 = -theta3;
t5 = t3+theta1;
t6 = t4+theta1;
t7 = t4+theta2;
t8 = cos(t5);
t9 = cos(t6);
t10 = cos(t7);
t11 = l1.*l3.*m3.*t9;
t12 = l2.*l3.*m3.*t10;
t13 = l1.*l2.*t2.*t8;
M = reshape([l1.^2.*(m1+t2),t13,t11,t13,l2.^2.*t2,t12,t11,t12,l3.^2.*m3],[3,3]);
